---
# tasks file for apache

- name: Installing httpd (Apache)
  apt:
    name: apache2
    state: latest
  register: Output

- name: start service httpd - if install succeeded
  service:
    name: apache2
    state: started
  when: Output is succeeded
  notify:
  - restart apache
...
